# Generated by Django 5.0.1 on 2024-02-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='form_filled_in',
            field=models.BooleanField(default='False'),
        ),
    ]
