# Generated by Django 5.0.1 on 2024-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='patient_csv/'),
        ),
    ]
