# Generated by Django 5.0.1 on 2024-02-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_csv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='csv_file',
        ),
        migrations.AddField(
            model_name='patient',
            name='csv_path',
            field=models.CharField(default='nan', max_length=100),
        ),
    ]
