# Generated by Django 5.0.1 on 2024-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_csv_file_patient_csv_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default='nan', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='antibiotic',
            field=models.CharField(default='nan', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(default='nan', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='nan', max_length=100),
        ),
    ]
