# Generated by Django 5.0.1 on 2024-02-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_linkclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkclick',
            name='patient_id',
            field=models.CharField(default='9999', max_length=50),
        ),
        migrations.AlterField(
            model_name='linkclick',
            name='link_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='page_name',
            field=models.CharField(max_length=50),
        ),
    ]
