# Generated by Django 5.0.1 on 2024-02-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_rename_csv_path_patient_vitals_csv_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patients_csv_path',
            new_name='patient_csv_path',
        ),
    ]
