# Generated by Django 5.0.1 on 2024-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_rename_patients_csv_path_patient_patient_csv_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='feature_similarity_path',
            field=models.CharField(default='nan', max_length=100),
        ),
    ]
