# Generated by Django 5.0.1 on 2024-02-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_feature_similarity_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='comorbidities',
            field=models.CharField(default='nan', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(default='nan', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='imddecil',
            field=models.CharField(default='nan', max_length=100),
        ),
    ]
