# Generated by Django 5.0.1 on 2024-02-14 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vitals_csv_path', models.CharField(default='nan', max_length=100)),
                ('patient_csv_path', models.CharField(default='nan', max_length=100)),
                ('similar_patients_csv_path', models.CharField(default='nan', max_length=100)),
                ('feature_similarity_path', models.CharField(default='nan', max_length=100)),
                ('age', models.CharField(default='nan', max_length=100)),
                ('sex', models.CharField(default='nan', max_length=100)),
                ('ethnicity', models.CharField(default='nan', max_length=100)),
                ('imddecil', models.CharField(default='nan', max_length=100)),
                ('comorbidities', models.CharField(default='nan', max_length=100)),
                ('diagnosis', models.CharField(default='nan', max_length=100)),
                ('antibiotic', models.CharField(default='nan', max_length=100)),
                ('prediction', models.CharField(default='nan', max_length=100)),
                ('guideline', models.CharField(default='nan', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('style', models.CharField(choices=[('success', 'Success'), ('danger', 'Danger'), ('info', 'Info'), ('warning', 'Warning')], max_length=50)),
                ('bg_class', models.CharField(default='bg-light', max_length=50)),
                ('text_class', models.CharField(default='text-dark', max_length=50)),
                ('decision_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.decisionpoint')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_value', models.CharField(max_length=50)),
                ('archetype', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
