# Generated by Django 5.0.1 on 2024-02-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_pagevisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='timestamp',
            new_name='entry_timestamp',
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='exit_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
