# Generated by Django 5.0.1 on 2024-03-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_rename_metric_hoverevent_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vitals_csv_path', models.CharField(default='nan', max_length=100)),
                ('patient_csv_path', models.CharField(default='nan', max_length=100)),
                ('similar_patients_csv_path', models.CharField(default='nan', max_length=100)),
                ('feature_similarity_path', models.CharField(default='nan', max_length=100)),
                ('age', models.CharField(default='nan', max_length=100)),
                ('sex', models.CharField(default='nan', max_length=100)),
                ('ethnicity', models.CharField(default='nan', max_length=100)),
                ('imddecil', models.CharField(default='nan', max_length=100)),
                ('comorbidities', models.CharField(default='nan', max_length=100)),
                ('diagnosis', models.CharField(default='nan', max_length=100)),
                ('antibiotic', models.CharField(default='nan', max_length=100)),
                ('prediction', models.CharField(default='nan', max_length=100)),
                ('guideline', models.CharField(default='nan', max_length=100)),
                ('form_filled_in', models.BooleanField(default=False)),
            ],
        ),
    ]
