FROM python:3

ENV PYTHONUNBUFFERED=1

WORKDIR /code

COPY requirements.txt .

RUN conda create --name tempenv --file requirements.txt

#RUN conda activate --name tempenv

COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "runserver"]





