# Generated by Django 5.0.1 on 2024-02-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table',
            new_name='Vitals_table',
        ),
    ]
